name: Android Build

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses:  actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Tests
        run: sudo ./gradlew test

      - name: Build Project
        run: sudo ./gradlew assemble